### ISSUE TITLE
Get Google Analytics code

### ISSUE THREAD

**Issue by naher94** [YasmeenAlmuhanna/yasmeenalmuhanna.com#1]

**Comment by YasmeenAlmuhanna** [comment]
UA-144583343-1

**Comment by YasmeenAlmuhanna** [comment]
^Tracking ID

**Comment by naher94** [comment]
there should be a bigger section of code that you use to paste into the page

**Comment by YasmeenAlmuhanna** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-144583343-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-144583343-1');
</script>

**Comment by naher94** [comment]
was this pulled from where this references it? for static site? https://support.google.com/analytics/answer/7476135?hl=en Looks different that what I have on my site but they have have changed it since...

**Comment by YasmeenAlmuhanna** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-144583343-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-144583343-1');
</script>

**Comment by YasmeenAlmuhanna** [comment]
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-144583343-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-144583343-1');
</script>

```

**Comment by naher94** [comment]
Shipped
