### ISSUE TITLE
super small switch

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#36]
Hi David!

Ben commented that it would make more sense to switch the project title name with the category. He says the category has more relevance to the employer than the name and I think he's right....

If you show me where to change that in the markdown file I can do it myself, I just can't find it.... 

![image](https://user-images.githubusercontent.com/13010867/64191042-9f2b6f80-ce45-11e9-9dbd-d0a385bff62c.png)

**Comment by naher94** [comment]
personally I think having the title up top shows more about the sense of the project since you want them the recruiter to look at your breath and the information architecture you have follows the logic of most important on the top then the category of work as a subset of that.... my 2 cents :P

**Comment by YasmeenAlmuhanna** [comment]
I'm just concerned that the name of the projects are too niche.... Like no one is going to know what 'Tactile Flux' means...

**Comment by dmbaker90** [comment]
Swapped
