### ISSUE TITLE
quick question, no code edit needed.

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#37]
So when I type: yasmeenalmuhanna.com the website loads beautifully.

But, if I add 'www.' before the website this page loads
![image](https://user-images.githubusercontent.com/13010867/64271912-3d820880-cf0c-11e9-894b-5e6e5c5ffbd2.png)

Any idea why that is? I'm worried that someone might type in www.yasmeenalmuhanna.com and not understand why they can't get to my site.....

**Comment by naher94** [comment]
We can fix this pretty easily.. we have to add a think to the DNS settings in Namecheap
