### ISSUE TITLE
switch generic world icon to black 'YA' logo in tab preview.

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#38]
![image](https://user-images.githubusercontent.com/13010867/64369126-ac815f00-cfe9-11e9-92c1-d08d7b7ffe1b.png)

**Comment by naher94** [comment]
This should already be happening as in the metadata there is a `<link rel="icon" type="image/png" href="../img/favicon.png">`

**Comment by naher94** [comment]
there also seems to be some issue with `<link rel="shortcut icon" type="image/png" href="../img/yalogo.svg">` reading an SVG rather then a PNG

**Comment by dmbaker90** [comment]
Seems to be Chrome only.  Works fine in Firefox

**Comment by dmbaker90** [comment]
I only see a "yalogoblack.afdesign" file, which I can't open.  But I changed **yalogo.svg** to **favicon.png** for the icon.

**Comment by dmbaker90** [comment]
Might have to clear cache
