### ISSUE TITLE
Easter Egg Size

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#39]
Would is be possible to decrease the size of the egg and overlay grass on top of it as shown below?
![image](https://user-images.githubusercontent.com/13010867/64376576-99c15700-cff6-11e9-8731-60d864c03050.png)

![image](https://user-images.githubusercontent.com/13010867/64376537-86ae8700-cff6-11e9-95fa-61b1361b340a.png)

**Comment by naher94** [comment]
should be decently easy.. will have to look at it to be sure but I would probs wrap both the egg and grass in a div and that way they can be positioned together if I didn't already wrap the egg in a container

**Comment by dmbaker90** [comment]
Let me know how it looks now
