### ISSUE TITLE
small fix

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#45]
Is it possible to layout these two images side by side as opposed to one on top of the other?
If that is too difficult, I can combine both of them into one long image. Just let me know.
![image](https://user-images.githubusercontent.com/13010867/64717358-2a35e680-d492-11e9-93f1-94db2d508e44.png)

**Comment by YasmeenAlmuhanna** [comment]
But also responsive, so in the mobile version it would be stacked since the screen is really narrow.

**Comment by dmbaker90** [comment]
Try now
