### ISSUE TITLE
Fuel + Co. hero image does not show

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#46]
Any idea why the hero image won't load? I changed the company name and maybe that's why?

![image](https://user-images.githubusercontent.com/13010867/64890343-69ed0180-d63d-11e9-8df2-9b73b26af150.png)

**Comment by dmbaker90** [comment]
It was the name, I changed the reference now.
