### ISSUE TITLE
New Markdown Page

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#47]
I copied the fuek nutrition markdown page for the new 'seated app' page but for some reason it's not behaving/laying out the same way. Refer to image below.

![image](https://user-images.githubusercontent.com/13010867/64890539-e67fe000-d63d-11e9-95b5-8f860f475b7a.png)

**Comment by dmbaker90** [comment]
It was missing a closing </div> tag, probably just deleted by accident.
