### ISSUE TITLE
Single line

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#48]
How did you get the project type to fill out on one line in the Meydan page rather than divide itself as shown in these two projects? I tried copying the Meydan markdown syntax but it didn't work...

![image](https://user-images.githubusercontent.com/13010867/64890875-8b022200-d63e-11e9-913a-d53b27712d28.png)

**Comment by dmbaker90** [comment]
They are both single lines for me in both Chrome and Firefox: 

![image](https://user-images.githubusercontent.com/5949263/64923243-07634500-d7a6-11e9-8532-a70104fcd9f4.png)
