### ISSUE TITLE
2 images to add to Fuel Nutrition

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#49]
I made some additions to the fuel page myself, but I do not know how to place two images side by side as shown below while also keeping them responsive so that they stack on top of one another when the screen is narrow.

The images have been uploaded to the fuelnutrition file.
pic1 = logoangles
pic2 = stationplanfullopacity
![image](https://user-images.githubusercontent.com/13010867/64893139-53967400-d644-11e9-8bfe-a6f33b3e65d4.png)

**Comment by dmbaker90** [comment]
Try now

**Comment by YasmeenAlmuhanna** [comment]
Beautiful

**Comment by YasmeenAlmuhanna** [comment]
crossfitinspo.svg disappeared though

![image](https://user-images.githubusercontent.com/13010867/64925780-9cc10200-d7c3-11e9-8ad6-f6b935aa3a08.png)

**Comment by dmbaker90** [comment]
Try now: https://yasmeenalmuhanna.com/fuelnutrition
