### ISSUE TITLE
White Space?

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#50]
No idea why there is a thin white space in the middle of the red underline under the heading.
Same exact code as all the other instances...

![image](https://user-images.githubusercontent.com/13010867/64898569-93b22280-d655-11e9-9df5-3682218bf600.png)

![image](https://user-images.githubusercontent.com/13010867/64898600-b80dff00-d655-11e9-881b-9c91e687fcfb.png)

**Comment by dmbaker90** [comment]
I don't see that in either Chrome or Firefox.  Do you still see it?

![image](https://user-images.githubusercontent.com/5949263/64923217-c9662100-d7a5-11e9-8d7f-a3e230509918.png)

**Comment by YasmeenAlmuhanna** [comment]
hmm...yesI do. No biggie I guess.

**Comment by dmbaker90** [comment]
I added a "fill" background color so if there was a line it should be red not white.
 
See if you still see it.

**Comment by YasmeenAlmuhanna** [comment]
WoWeE!! It's gone!
