### ISSUE TITLE
thumbnail too long

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#51]
Cookie Caricature's thumbnail is longer than the others. I made the cookie face smaller but the thumbnail did not resize. Perhaps the solution pertains to the text? Help needed here.

![image](https://user-images.githubusercontent.com/13010867/64910211-d02b6000-d6e1-11e9-823c-f317e497c196.png)

**Comment by dmbaker90** [comment]
I set a max size to the inner img: https://yasmeenalmuhanna.com/
