### ISSUE TITLE
Api Link

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#57]
I don't know how to lay this out. I have 6 API's I want to show here in a grid. They are all saved under the 'seatedapp' img folder.
Desired hover effect: Enlarge logo slightly when mouse hovers over one.

Links in order from left to right:

https://api.ticketbud.com/
https://www.ticketmatic.com/docs/api/
https://www.twilio.com/docs/usage/api
https://checkr.com/
https://developers.google.com/maps/documentation/
https://developers.google.com/web/fundamentals/native-hardware/click-to-call/

![image](https://user-images.githubusercontent.com/13010867/64925518-a0eb2080-d7bf-11e9-8426-6969b89b403f.png)

**Comment by dmbaker90** [comment]
Done

**Comment by dmbaker90** [comment]
Fixed them in Chrome

**Comment by YasmeenAlmuhanna** [comment]
Amazing.
