### ISSUE TITLE
padding help

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#66]
IS it possible to decrease the size of these two images so that they aren't as big and touching each other....more like the blue outline shown.
![image](https://user-images.githubusercontent.com/13010867/65379077-8d90f700-dc90-11e9-9795-9a7f532f88c8.png)

**Comment by YasmeenAlmuhanna** [comment]
I think it's a padding issue. Just don't know how to add it.

**Comment by dmbaker90** [comment]
I've configured it so if you add the class "img-padding" it adds spacing when images use both columns.  Like this: 

> <div class="columns">
     <div class="left-column-img img-padding">
         <img src="/img/mywebsite/Github.png" alt="Github Img">
     </div>
     <div class="right-column-img img-padding">
        <img src="/img/mywebsite/atom.png" alt="Code Img">
    </div>
</div> 

try now: https://yasmeenalmuhanna.com/cookiecaricature
