### ISSUE TITLE
Heading aesthetic change when only one line

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#67]
I copied the heading over in cookie caricature but the arrangement/hierarchy changes when the heading is only one word versus a two line sentence. See below for reference.
If this is too complicated then don't worry about it and I can just change it to a two-liner.
![image](https://user-images.githubusercontent.com/13010867/65379107-e2cd0880-dc90-11e9-9381-d294956501a9.png)

**Comment by dmbaker90** [comment]
Put the line break in the beggining so it's basically still 2 lines: `<h2><br/>Process</h2>`

https://yasmeenalmuhanna.com/cookiecaricature
