### ISSUE TITLE
Footnote color

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#69]
Would it be possible to change the blue text to white?
![image](https://user-images.githubusercontent.com/13010867/65381039-26863900-dcb6-11e9-974f-daf0d0fc5640.png)
![image](https://user-images.githubusercontent.com/13010867/65381043-533a5080-dcb6-11e9-9fba-ef37be7be4bb.png)

**Comment by YasmeenAlmuhanna** [comment]
Also, issue number 69 :)

**Comment by dmbaker90** [comment]
Try now :)
