### ISSUE TITLE
How to make additional thumbnail page for website process (Easter Egg Page?)

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#70]
Hello.
How can I make a new markdown file for the easter egg file?

**Comment by dmbaker90** [comment]
I'm not sure what you mean by this, maybe we should chat

**Comment by YasmeenAlmuhanna** [comment]
I figured it out myself thanks! But we should still chat.
