### ISSUE TITLE
Squished images on website process page

### ISSUE THREAD

**Issue by YasmeenAlmuhanna** [YasmeenAlmuhanna/yasmeenalmuhanna.com#71]
This is what the website process looks like on Rehan's monitor. Looks fine on my computer, but not his....
The squished images are (Landing Page 1-4 and Fuel Nutrition 1-4). 

![image](https://user-images.githubusercontent.com/13010867/66434182-f8ac2e80-e9ef-11e9-909e-e5339f90be25.png)

**Comment by dmbaker90** [comment]
Fixed as well.  I believe.  I don't normally test Safari, and it always does things differently for some reason.
